In [6]:
import os
import glob
import numpy as np
import pandas as pd
import copy
import mne
from fooof import FOOOF, FOOOFGroup
import re

In [9]:
df_localization = pd.read_csv('/Volumes/Nexus/Users/zouj/sEEG_data/electrode-localizations.tsv', delimiter='\t')\
    [['Subject', 'label', 'electrode', 'is_thalamic', 'is_cortical']]
spectra_file_names = glob.glob('/Volumes/Nexus/Users/zouj/sEEG_data/spectra/*')
ch_dict = {}
for spectra_file in spectra_file_names:
    subject_pattern = r'EM\d{4}'
    subject = re.findall(subject_pattern, os.path.basename(spectra_file))[0]
    if subject not in ch_dict:
        spectra = mne.time_frequency.read_spectrum(spectra_file)
        ch_dict[subject] = spectra.ch_names
file_basenames = [os.path.basename(file_path) 
                  for file_path in glob.glob('/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/fooof*100*/fits/*')]

In [77]:
glob.glob('/Volumes/Nexus/Users/zouj/sEEG_data/spectra/*')

['/Volumes/Nexus/Users/zouj/sEEG_data/spectra/sub-EM1021_session-EMU_task-resting_run-01-spectrum.h5',
 '/Volumes/Nexus/Users/zouj/sEEG_data/spectra/sub-EM1021_session-EMU_task-resting_run-02-spectrum.h5',
 '/Volumes/Nexus/Users/zouj/sEEG_data/spectra/sub-EM1021_session-EMU_task-resting_run-03-spectrum.h5',
 '/Volumes/Nexus/Users/zouj/sEEG_data/spectra/sub-EM1023_ses-EMU_task-resting_run-02-spectrum.h5',
 '/Volumes/Nexus/Users/zouj/sEEG_data/spectra/sub-EM1023_ses-EMU_task-resting_run-01-spectrum.h5',
 '/Volumes/Nexus/Users/zouj/sEEG_data/spectra/sub-EM1029_ses-EMU_task-resting_run-01-spectrum.h5',
 '/Volumes/Nexus/Users/zouj/sEEG_data/spectra/EM1002_ses-EMU_task-resting_run-1_1-spectrum.h5',
 '/Volumes/Nexus/Users/zouj/sEEG_data/spectra/EM1002_ses-EMU_task-resting_run-1_2-spectrum.h5',
 '/Volumes/Nexus/Users/zouj/sEEG_data/spectra/EM1035_ses-EMU_task-resting_run-1-spectrum.h5',
 '/Volumes/Nexus/Users/zouj/sEEG_data/spectra/sub-EM1061_ses-EMU_task-resting_run-01_ieeg-spectrum.h5',
 '/V

# Regularization Weight

In [2]:
spectra_file =  '/Volumes/Nexus/Users/zouj/sEEG_data/spectra/sub-EM1029_ses-EMU_task-resting_run-01-spectrum.h5'
spectra =mne.time_frequency.read_spectrum(spectra_file)

In [3]:
spectra.pick(['LCM1', 'LCM2', 'LCM3', 'LCM4', 'LCM5', 'LCM6', 'LCM7', 'LCM8'])

<Power Spectrum (from Raw, welch method) | 8 channels × 513 freqs, 0.0-512.0 Hz>

In [4]:
fg4 = FOOOFGroup(peak_width_limits=[2,25],
                  max_n_peaks = 6,
                  min_peak_height = 0.15,
                  peak_threshold = 2,
                  bw_std_edge = 1, 
                  aperiodic_mode = 'lorentzian',
                  regularization_weight = 10**4
                  )
    
fg4.fit(spectra.freqs, spectra.get_data(), freq_range = [1, 150])

Running FOOOFGroup across 8 power spectra.
-----
guess for fitting [[ 7.          0.29106329  1.6986436 ]
 [30.          0.19281717  2.5479654 ]]
fitted gaussian_params [[ 7.5044919   0.32141404  1.14497305]
 [28.78471581  0.18632394  3.42411255]]
-----
guess for fitting [[ 7.          0.25818053  1.6986436 ]
 [30.          0.33261048  3.3972872 ]]
fitted gaussian_params [[ 7.25113453  0.28751479  1.09030046]
 [29.69685716  0.30608591  3.53002637]]
-----
guess for fitting [[ 7.          0.16663059  1.6986436 ]
 [29.          0.44458153  4.246609  ]]
fitted gaussian_params [[ 7.51561121  0.19121095  1.12137971]
 [29.74872962  0.47869413  4.28317046]]
-----
guess for fitting [[29.          0.68261994  4.246609  ]]
fitted gaussian_params [[29.17814988  0.67885623  4.19473165]]
-----
guess for fitting [[ 7.          0.34173824  2.5479654 ]
 [30.          0.27257945  3.3972872 ]]
fitted gaussian_params [[ 6.55214964  0.4561262   1.        ]
 [29.64640527  0.26340413  2.9313362 ]]
-----
gues

In [5]:
fg4.get_fooof(2).save_report('/Volumes/Nexus/Users/zouj/sEEG_data/LCM3-r4.png', plt_log = True)
fg4.get_fooof(3).save_report('/Volumes/Nexus/Users/zouj/sEEG_data/LCM4-r4.png', plt_log = True)
fg4.get_fooof(4).save_report('/Volumes/Nexus/Users/zouj/sEEG_data/LCM5-r4.png', plt_log = True)
fg4.get_fooof(5).save_report('/Volumes/Nexus/Users/zouj/sEEG_data/LCM6-r4.png', plt_log = True)

/Users/jasminezou/Projects/fooof/fooof/plts/style.py:172: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout()
/Users/jasminezou/Projects/fooof/fooof/plts/style.py:172: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout()
/Users/jasminezou/Projects/fooof/fooof/plts/style.py:172: UserWarning: The figure layout has changed to tight
  plt.tight_layout()
/Users/jasminezou/Projects/fooof/fooof/plts/style.py:172: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout()
/Users/jasminezou/Projects/fooof/fooof/plts/style.py:172: UserWarning: The figure layout has changed to tight
  plt.tight_layout()
/Users/jasminezou/Projects/fooof/fooof/plts/style.py:172: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be in

## Data Wrangling - PW25

In [7]:
dir_list = ['/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/fooof_1-100hz_r4_bw1_pw25/fits',
            '/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/fooof_1-150hz_r4_bw1_pw25/fits',
            '/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/fooof_1-200hz_r4_bw1_pw25/fits']
results_df_list = []

In [10]:
subject_col = []
ch_col = []
dir_col = []
run_col = []
for dir in dir_list:
    dir_name = os.path.basename(os.path.dirname(dir))
    for file in file_basenames:
        subject_pattern = r'EM\d{4}'
        subject = re.findall(subject_pattern, file)[0]

        run_pattern = r'run-\d[^a-zA-Z]*'
        run = re.findall(run_pattern, file)[0][:-1]

        fg = FOOOFGroup()
        fg.load(file, dir)

        for i in range(len(fg)):
            fooof = fg[i]#.get_fooof(i)
            gauss_params = fooof.gaussian_params
            CF, PW, BW = gauss_params[:, 0], gauss_params[:, 1], gauss_params[:, 2]
            if not np.all(CF - 1 > BW):
                print(dir, subject, run, ch_dict[subject][i], CF)
                subject_col.append(subject)
                ch_col.append(ch_dict[subject][i])
                dir_col.append(dir_name)
                run_col.append(run)

In [12]:
poor_peak_fit = pd.DataFrame(np.array([dir_col, run_col, subject_col, ch_col]).T, columns = ['dir', 'run', 'Subject', 'ch'])
poor_peak_fit.to_csv('/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/lorentzian-poor_peak_fit-pw25.csv')

## Data Wrangling - PW50

In [36]:
dir_list = ['/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/fooof_1-100hz_r4_bw1/fits',
            '/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/fooof_1-150hz_r4_bw1/fits',
            '/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/fooof_1-200hz_r4_bw1/fits']
results_df_list = []

18

In [69]:
subject_col = []
ch_col = []
dir_col = []
run_col = []
for dir in dir_list:
    dir_name = os.path.basename(os.path.dirname(dir))
    for file in file_basenames:
        subject_pattern = r'EM\d{4}'
        subject = re.findall(subject_pattern, file)[0]

        run_pattern = r'run-\d[^a-zA-Z]*'
        run = re.findall(run_pattern, file)[0][:-1]

        fg = FOOOFGroup()
        fg.load(file, dir)

        for i in range(len(fg)):
            fooof = fg[i]#.get_fooof(i)
            gauss_params = fooof.gaussian_params
            CF, PW, BW = gauss_params[:, 0], gauss_params[:, 1], gauss_params[:, 2]
            if not np.all(CF - 1 > BW):
                print(dir, subject, run, ch_dict[subject][i], CF)
                subject_col.append(subject)
                ch_col.append(ch_dict[subject][i])
                dir_col.append(dir_name)
                run_col.append(run)

/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/fooof_1-100hz_r4_bw1/fits EM1023 run-02 LPI8 [ 8.9040692  60.02824037]
/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/fooof_1-100hz_r4_bw1/fits EM1023 run-02 LPI10 [15.24941738]
/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/fooof_1-100hz_r4_bw1/fits EM1023 run-02 LPI12 [3.8081384]
/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/fooof_1-100hz_r4_bw1/fits EM1023 run-02 RPI3 [ 7.61028229  8.9040692  60.66390598]
/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/fooof_1-100hz_r4_bw1/fits EM1023 run-02 RPI5 [ 9.86174792 68.739827  ]
/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/fooof_1-100hz_r4_bw1/fits EM1023 run-01 LPI12 [1.260173]
/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/fooof_1-100hz_r4_bw1/fits EM1023 run-01 RCM8 [ 2.         21.92770015]
/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/fooof_1-100hz_r4_bw1/fits EM1023 run-01 RPI5 [ 6.3561038  17.60791738 57.52768022]
/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outp

In [71]:
poor_peak_fit = pd.DataFrame(np.array([dir_col, run_col, subject_col, ch_col]).T, columns = ['dir', 'run', 'Subject', 'ch'])

In [72]:
poor_peak_fit.to_csv('/Volumes/Nexus/Users/zouj/sEEG_data/fooof_outputs/poor_peak_fit_pw50.csv')

In [32]:
for fooof in fg.group_results:
    gauss_params = fooof.gaussian_params
    CF, PW, BW = gauss_params[:, 0], gauss_params[:, 1], gauss_params[:, 2]
    print(CF - 1 >BW)

[ True]
[ True]
[ True]
[ True  True]
[ True  True]
[ True  True  True]
[ True  True]
[ True  True]
[ True  True  True]
[ True]
[ True  True  True]
[ True  True  True  True]
[ True  True  True]
[ True]
[ True  True  True]
[ True]
[ True  True  True]
[ True  True  True  True  True  True]
